on: push
name: On git push deploy to AWS
jobs:
  installNodeModules:
    name: Install node modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install node modules
      uses: actions/npm@de7a3705a9510ee12702e124482fad6af249991b
      with:
        entrypoint: npm
        args: install
    - name: Serverless Deploy
      uses: actions/npm@de7a3705a9510ee12702e124482fad6af249991b
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        entrypoint: npm
        args: run deploy
